"""Initial PostgreSQL setup

Revision ID: 0e4b8e015a7f
Revises:
Create Date: 2025-12-04 12:19:33.352106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4b8e015a7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ===== USERS (must be created before audit_logs due to FK) =====
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('temp_password_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ===== AUDIT LOGS =====
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('affected_styles_count', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('cleaning_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garment_type', sa.String(length=50), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=False),
    sa.Column('avg_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garment_type')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colors_name'), ['name'], unique=True)

    op.create_table('fabric_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vendor_code', sa.String(length=20), nullable=True),
    sa.Column('f_ship_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('labor_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost_type', sa.String(length=20), nullable=False),
    sa.Column('fixed_cost', sa.Float(), nullable=True),
    sa.Column('cost_per_hour', sa.Float(), nullable=True),
    sa.Column('cost_per_piece', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notion_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vendor_code', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_table('size_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('regular_sizes', sa.String(length=100), nullable=False),
    sa.Column('extended_sizes', sa.String(length=100), nullable=True),
    sa.Column('extended_markup_percent', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('size_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=10), nullable=False),
    sa.Column('size_category', sa.String(length=20), nullable=False),
    sa.Column('price_multiplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_style', sa.String(length=50), nullable=False),
    sa.Column('base_item_number', sa.String(length=20), nullable=True),
    sa.Column('variant_code', sa.String(length=20), nullable=True),
    sa.Column('style_name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('garment_type', sa.String(length=50), nullable=True),
    sa.Column('size_range', sa.String(length=50), nullable=True),
    sa.Column('base_margin_percent', sa.Float(), nullable=True),
    sa.Column('avg_label_cost', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_styles_base_margin_percent'), ['base_margin_percent'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_garment_type'), ['garment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_style_name'), ['style_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_styles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_vendor_style'), ['vendor_style'], unique=True)

    op.create_table('variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variables_name'), ['name'], unique=True)

    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_codes_email'), ['email'], unique=True)

    op.create_table('fabrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fabric_code', sa.String(length=20), nullable=False),
    sa.Column('cost_per_yard', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('fabric_vendor_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fabric_vendor_id'], ['fabric_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fabric_code')
    )
    with op.batch_alter_table('fabrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fabrics_fabric_vendor_id'), ['fabric_vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fabrics_name'), ['name'], unique=False)

    op.create_table('notions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=True),
    sa.Column('notion_vendor_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notion_vendor_id'], ['notion_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notions_notion_vendor_id'), ['notion_vendor_id'], unique=False)

    op.create_table('style_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'color_id', name='uq_style_color')
    )
    with op.batch_alter_table('style_colors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_colors_color_id'), ['color_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_colors_style_id'), ['style_id'], unique=False)

    op.create_table('style_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_images_style_id'), ['style_id'], unique=False)

    op.create_table('style_labor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('labor_operation_id', sa.Integer(), nullable=False),
    sa.Column('time_hours', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['labor_operation_id'], ['labor_operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'labor_operation_id', name='uq_style_labor')
    )
    with op.batch_alter_table('style_labor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_labor_labor_operation_id'), ['labor_operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_labor_style_id'), ['style_id'], unique=False)

    op.create_table('style_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'variable_id', name='uq_style_variable')
    )
    with op.batch_alter_table('style_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_variables_style_id'), ['style_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_variables_variable_id'), ['variable_id'], unique=False)

    op.create_table('style_fabrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('yards_required', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_sublimation', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'fabric_id', name='uq_style_fabric')
    )
    with op.batch_alter_table('style_fabrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_fabrics_fabric_id'), ['fabric_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_fabrics_style_id'), ['style_id'], unique=False)

    op.create_table('style_notions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('notion_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['notion_id'], ['notions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('style_id', 'notion_id', name='uq_style_notion')
    )
    with op.batch_alter_table('style_notions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_notions_notion_id'), ['notion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_notions_style_id'), ['style_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_notions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_notions_style_id'))
        batch_op.drop_index(batch_op.f('ix_style_notions_notion_id'))

    op.drop_table('style_notions')
    with op.batch_alter_table('style_fabrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_fabrics_style_id'))
        batch_op.drop_index(batch_op.f('ix_style_fabrics_fabric_id'))

    op.drop_table('style_fabrics')
    with op.batch_alter_table('style_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_variables_variable_id'))
        batch_op.drop_index(batch_op.f('ix_style_variables_style_id'))

    op.drop_table('style_variables')
    with op.batch_alter_table('style_labor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_labor_style_id'))
        batch_op.drop_index(batch_op.f('ix_style_labor_labor_operation_id'))

    op.drop_table('style_labor')
    with op.batch_alter_table('style_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_images_style_id'))

    op.drop_table('style_images')
    with op.batch_alter_table('style_colors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_colors_style_id'))
        batch_op.drop_index(batch_op.f('ix_style_colors_color_id'))

    op.drop_table('style_colors')
    with op.batch_alter_table('notions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notions_notion_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_notions_name'))

    op.drop_table('notions')
    with op.batch_alter_table('fabrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fabrics_name'))
        batch_op.drop_index(batch_op.f('ix_fabrics_fabric_vendor_id'))

    op.drop_table('fabrics')
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_codes_email'))

    op.drop_table('verification_codes')
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variables_name'))

    op.drop_table('variables')
    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_styles_vendor_style'))
        batch_op.drop_index(batch_op.f('ix_styles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_styles_style_name'))
        batch_op.drop_index(batch_op.f('ix_styles_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_styles_is_active'))
        batch_op.drop_index(batch_op.f('ix_styles_gender'))
        batch_op.drop_index(batch_op.f('ix_styles_garment_type'))
        batch_op.drop_index(batch_op.f('ix_styles_created_at'))
        batch_op.drop_index(batch_op.f('ix_styles_base_margin_percent'))

    op.drop_table('styles')
    op.drop_table('size_variants')
    op.drop_table('size_ranges')
    op.drop_table('notion_vendors')
    op.drop_table('labor_operations')
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_settings_setting_key'))

    op.drop_table('global_settings')
    op.drop_table('fabric_vendors')
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colors_name'))

    op.drop_table('colors')
    op.drop_table('cleaning_costs')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###