"""Remove unique constraint on style_fabrics to allow duplicate fabrics

Revision ID: 252fa85f19ac
Revises: 370d13f146f3
Create Date: 2026-01-22 09:59:48.419616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252fa85f19ac'
down_revision = '370d13f146f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_costs', schema=None) as batch_op:
        batch_op.drop_constraint('cleaning_costs_garment_type_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_cleaning_costs_garment_type'), ['garment_type'], unique=True)

    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_styles_style_name'), ['style_name'], unique=False)

    # Remove unique constraint on style_fabrics to allow same fabric multiple times
    with op.batch_alter_table('style_fabrics', schema=None) as batch_op:
        batch_op.drop_constraint('uq_style_fabric', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_fabrics', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_style_fabric', ['style_id', 'fabric_id'])

    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_styles_style_name'))

    with op.batch_alter_table('cleaning_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_costs_garment_type'))
        batch_op.create_unique_constraint('cleaning_costs_garment_type_key', ['garment_type'])

    # ### end Alembic commands ###