"""Add database indexes

Revision ID: 9d88d1fe32a3
Revises: 
Create Date: 2025-11-26 10:22:31.868352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d88d1fe32a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sublimation_cost')
    op.drop_table('settings')
    with op.batch_alter_table('fabric_vendors', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('fabrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fabrics_fabric_vendor_id'), ['fabric_vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fabrics_name'), ['name'], unique=False)

    with op.batch_alter_table('notion_vendors', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('notions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notions_notion_vendor_id'), ['notion_vendor_id'], unique=False)

    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_styles_base_margin_percent'), ['base_margin_percent'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_garment_type'), ['garment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_style_name'), ['style_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_styles_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_styles_vendor_style'), ['vendor_style'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_styles_vendor_style'))
        batch_op.drop_index(batch_op.f('ix_styles_updated_at'))
        batch_op.drop_index(batch_op.f('ix_styles_style_name'))
        batch_op.drop_index(batch_op.f('ix_styles_is_favorite'))
        batch_op.drop_index(batch_op.f('ix_styles_is_active'))
        batch_op.drop_index(batch_op.f('ix_styles_gender'))
        batch_op.drop_index(batch_op.f('ix_styles_garment_type'))
        batch_op.drop_index(batch_op.f('ix_styles_created_at'))
        batch_op.drop_index(batch_op.f('ix_styles_base_margin_percent'))

    with op.batch_alter_table('notions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notions_notion_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_notions_name'))

    with op.batch_alter_table('notion_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('fabrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fabrics_name'))
        batch_op.drop_index(batch_op.f('ix_fabrics_fabric_vendor_id'))

    with op.batch_alter_table('fabric_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sublimation_cost',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cost_per_yard', sa.FLOAT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
